config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :events
    resources :participants
    resources :entries
    resources :songs
    resources :artists

    root to: "users#index"
  end

  root to: 'visitors#index'

  resources :events do
    member do
      get :live, :load_remote
    end
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, inverse_of: :artist
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :song, optional: true
  belongs_to :event
  belongs_to :participant, optional: true

  def break_or_name
    if break_flag
      "BREAK"
    else
      "#{participant.code}-#{song.code}-#{song.machine}"
    end
  end

  def long_display
    "#{song.title} - #{song.artist.name}"
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :entry, optional: true

  has_many :participants, inverse_of: :event
  has_many :entries, inverse_of: :event

  def status
    if start_at > Time.now
      :setup
    elsif end_at < Time.now
      :finished
    elsif entry.nil? || entry.break_flag
      :break
    else
      :active
    end
  end

  def next_5
    query = Entry.order(:order_no).limit(5)
    if entry.present?
      query = query.where("order_no > ?", entry.order_no)
    end
    query
  end

  def next_5_timestamp
    @next_5_timestamp ||=
      next_5.all.sort { |x, y| y.updated_at <=> x.updated_at }.first.try(:updated_at)
  end

  def summary_hash
    {
      status: status.to_s,
      next_5_timestamp: next_5_timestamp.iso8601,
      current_id: entry_id
    }
  end

  def summary_json
    JSON.generate(summary_hash)
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  has_many :entries, inverse_of: :song
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      authenticate_user!
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/artists_controller.rb
module Admin
  class ArtistsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Artist.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Artist.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/entries_controller.rb
module Admin
  class EntriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Entry.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Entry.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/participants_controller.rb
module Admin
  class ParticipantsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Participant.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Participant.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/songs_controller.rb
module Admin
  class SongsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Song.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Song.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :load_event

  def show
  end

  def live
    # next 5 songs, next song
    # current song
    respond_to do |format|
      format.html
      format.json { render json: @event.summary_hash }
    end
  end

  def load_remote
  end

  private

  def load_event
    @event = Event.includes(entry: [:participant, { song: :artist }], entries: [ :participant, {song: :artist} ]).find_by_slug! params[:id]
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_current_entry.html.haml
- if @event.status == :break
  %h1.break Break Time, please wait...
- elsif @event.status == :active
  %h1= @event.entry.long_display
  .form-group
    %textarea.form-control#lyrics{ readonly: true, rows: 5 }= @event.entry.song.lyrics

app/views/events/_next_five.html.haml
- if @event.status == :setup
  %h1= "#{@event.name} setting up"
- elsif @event.status == :finished
  %h1= "#{@event.name} finished"
  %p
    = link_to "back to event", event_path(@event.slug)
- elsif @event.next_5.present?
  - if @event.next_5.length > 1
    #next-5
      upcoming: 
      - @event.next_5.to_a.slice(1,5).each do |event|
        %strong= event.break_or_name

  - entry = @event.next_5.first
  #next-song
    next:
    - if entry.break_flag
      %strong BREAK
    - else
      %strong #{entry.song.title} - #{entry.song.artist.name} (#{entry.participant.code})

app/views/events/live.html.haml
#next-songs
  = render 'next_five'

#current-song
  = render 'current_entry'

:javascript
  document.body.style.height = window.innerHeight + "px";

  window.onkeydown = function (e) {
    var lyrics = document.getElementById('lyrics');
    if (e.code === "KeyB" || e.code === "PageDown") {
      lyrics.scrollTop += lyrics.clientHeight / 5;
      e.preventDefault();
    } else if (e.code === "F5" || e.code === "Escape" || e.code === "PageUp") {
      lyrics.scrollTop -= lyrics.clientHeight / 5;
      e.preventDefault();
    }
  }

  window.summary = #{raw @event.summary_json}

  function updateLive() {
    $.get('#{live_event_path(id: @event.slug, format: :json)}', {},
      function(data) {
        console.log(data);
        var param = null;
        if (window.summary.status !== data.status ||
        (window.summary.current_id !== data.current_id)) { 
          param = "all";
        } else if (window.summary.next_5_timestamp !== data.next_5_timestamp) {
          param = "next_5";
        } else if (window.summary.current_id !== data.current_id) {
          param = "current";
        }
        console.log(param)
        if (param) {
          $.get('#{load_remote_event_path(id: @event.slug, format: :js)}', { section: param });
        }
        window.summary = data;
      }
    );
  /*
    set state

    for interval

    get state

    if status different

      reload all 3

    else

      check last update of all next 2-5, reload if changed
      check id of next 1, reload if
      check id of current, reload if

      change summary

  */
  }

  window.setInterval(updateLive, 10000);

app/views/events/load_remote.js.erb
<% if params[:section] == "all" || params[:section] == "next_5" %>
  $("#next-songs").html("<%= j render 'next_five' %>")
<% end %>
<% if params[:section] == "all" || params[:section] == "current" %>
  $("#current-song").html("<%= j render 'current_entry' %>")
<% end %>

app/views/events/show.html.haml
%h1= @event.name

- if @event.url.present?
  %p
    %small= link_to @event.url, @event.url

= simple_format @event.description

%strong= link_to "View current status", live_event_path(@event.slug)

%h2 Set List

%table.table.table-sm
  %thead
    %tr
      %th #
      %th Singer code
      %th Song code
      %th Song
      %th Artist
  %tbody
    - @event.entries.order(:order_no).each_with_index do |entry, idx|
      %tr{ class: (entry.id == @event.entry_id ? "table-active" : "") }
        %td= idx + 1
        - if entry.break_flag
          %td.text-center{colspan: 4,class: (entry.id == @event.entry_id ? "table-active" : "table-info")} BREAK
        - else
          %td= entry.participant.code
          %td= entry.song.code
          %td= entry.song.title
          %td= entry.song.artist.name

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <%#<li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' ></li>%>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <%#<li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' ></li>%>
<% end %>

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-dark.navbar-inverse.bg-inverse.navbar-toggleable-md
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{ :href => root_url } JKaraokePH

  #exCollapsingNavbar2.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to "Home", root_path, class: 'nav-link'
      -#= render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Karaoke Manager2017'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Karaoke Manager2017'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    - if action_name != 'live'
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/visitors/index.html.erb
<h3>Welcome to our new karaoke managing tool</h3>

<p><em>still WIP</em></p>
<p>Current events:</p>

<% Event.all.each do |event| %>
  <p><%= link_to event.name, event_path(event.slug) %></p>
<% end %>